### ISSUE TITLE
Chat window name

### ISSUE THREAD

**Issue by TechJedi51** [hmijail/announce-zoom-chat-messages#1]
Thanks for creating this script. Just what I was looking for.

After the last update to Zoom, it appears that the Chat window name that was "chat" is now "Chat". But even when I change that in the script, it seems to be having trouble detecting the window. [See ScreenShot]

![Screenshot Zoom](https://user-images.githubusercontent.com/28914268/110192112-02061a00-7de1-11eb-961b-87a646994e83.png)

**Comment by hmijail** [comment]
Fixed to work on Zoom 5.6.1.

**Comment by hmijail** [comment]
(Sorry, I just realized that I hadn't actually pushed the changes! Done now)
